# 数据库配置
[mysql]
username = "root"
password = "yourpwdhere"
net = "tcp"
addr = "localhost"
dbname = "douyin"
charset = "utf8mb4"
parse_time = true
loc = "Local"
[jwt]
secretKey = "YourSecretKeyHere,ReplaceBeforeProduction"
[redis]
net = "tcp"
address = "localhost"
password = "yourpwdhere"